import { ResourceOptions } from "adminjs";

export const mediaProductResourceOptions: ResourceOptions = {
  navigation: "Produtos de Mídia",
  editProperties: [
    "title",
    "sinopsys",
    "status",
    "isEpisodic",
    "launchDate",
    "endDate",
    "totalEpisodes",
    "currentEpisode",
    "releaseDate",
    "thumbImg",
    "bannerImg",
    "categoryId",
  ],
  filterProperties: [
    "title",
    "sinopsys",
    "status",
    "isEpisodic",
    "launchDate",
    "endDate",
    "totalEpisodes",
    "currentEpisode",
    "releaseDate",
    "thumbImg",
    "bannerImg",
    "categoryId",
    "createdAt",
    "updatedAt",
  ],
  listProperties: [
    "title",
    "status",
    "isEpisodic",
    "launchDate",
    "endDate",
    "categoryId",
  ],
  showProperties: [
    "id",
    "title",
    "sinopsys",
    "status",
    "isEpisodic",
    "launchDate",
    "endDate",
    "totalEpisodes",
    "currentEpisode",
    "releaseDate",
    "thumbImg",
    "bannerImg",
    "categoryId",
    "createdAt",
    "updatedAt",
  ],
};
